### ISSUE TITLE
Slave address

### ISSUE THREAD

**Issue by Hantse** [mjmeans/Adafruit.IoT#3]
Hello,

I try to use library and your sample but i've this error : 

One or more errors occurred. (One or more errors occurred. (The system cannot find the file specified.

Slave address was not acknowledged.))

**Comment by mjmeans** [comment]
If you plan on contributing to this project create a branch to work in. Then double check the references. The error you refer to is not specific enough for me to trace. But it sounds like you need to check the projects references and resolve them.

If you are just trying to use the library for your own project, you should use the NuGet package instead of a fork of the project.

**Comment by Hantse** [comment]
Ok, the problems is the new version of Windows IOT Core :) Not your library ;) Work fine on older Windows IOTCORE Version :))
